# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x04ride\"U\n\x0bRideRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x04 \x01(\t\"\x1f\n\x0cRideResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2D\n\x0bRideService\x12\x35\n\nCreateRide\x12\x11.ride.RideRequest\x1a\x12.ride.RideResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RIDEREQUEST']._serialized_start=23
  _globals['_RIDEREQUEST']._serialized_end=108
  _globals['_RIDERESPONSE']._serialized_start=110
  _globals['_RIDERESPONSE']._serialized_end=141
  _globals['_RIDESERVICE']._serialized_start=143
  _globals['_RIDESERVICE']._serialized_end=211
# @@protoc_insertion_point(module_scope)
